### PR TITLE
Change buttons from hide/show actions to tabs. Updates #3

### PR DESCRIPTION
**Pull request by Le-Roi777**
- Updates #3

- Updated menu component to use tabs.
- Minor style update for home and clusterInfo components to accommodate tabs.
- As discussed I have added the details(clusterInfo) to the tabs menu instead of using an accordion as it might be a bit overkill. There is still a lot of space left for the details that might be handy later on. If that is not the case and the details will always be wat they are now, we can simply add it to a footer in a more subtle way.

### CODE REVIEW

**Comment by andreaspeters** [comment]
Thanks @Le-Roi777 for your contribution. :-)

**Comment by Le-Roi777** [comment]
> Thanks @Le-Roi777 for your contribution. :-)

You're welcome :-)
I think the UI for all the data components can also be improved a lot so if ever you need any more help please feel free to get in touch.

**Comment by andreaspeters** [comment]
Thanks again. Feel free to improve the UI. :sweat_smile: I'm open for PR's even without issues from my site. :-D

**Comment by Le-Roi777** [comment]
> Thanks again. Feel free to improve the UI. 😅 I'm open for PR's even without issues from my site. :-D

Sounds good 👍 I'll stay in touch :-)

**Pull request merged**
