### PR TITLE
Button Created for Starting and Stopping Agents

### LINKED ISSUE #2: Create button to stop and start Apache Mesos
Create one  button to stop and start the following services at once:

- Apache Mesos Master 
- Apache Mesos Agent
- Apache Zookeeper

Needed features:

- Check if the service is already running before show a state specific icon
- Start and stop the specific service process

### PR DESCRIPTION
**Pull request by gagandeepp**
Fixes https://github.com/AVENTER-UG/docker-mesos-extension/issues/2

### CODE REVIEW

**Comment by gagandeepp** [comment]
@andreaspeters  Please review this

**Comment by andreaspeters** [comment]
@gagandeepp Please check if the service is already running to perform the corresponding action (stop, start). And one button for all services is fine. It does not have to be one for each service.  :-)

**Comment by gagandeepp** [comment]
> @gagandeepp Please check if the service is already running to perform the corresponding action (stop, start). And one button for all services is fine. It does not have to be one for each service. :-)

How to check the which services are running ?

**Comment by andreaspeters** [comment]
I think it would work with this one: https://docs.docker.com/desktop/extensions-sdk/dev/api/reference/interfaces/HttpService/

Use the GET method to read the Mesos state `localhost:5050/state`. If you will not get an error, zookeeper and the Mesos Master service are running. And then we just assume that the Agent is also running. Keep it simple. :-)

**Comment by gagandeepp** [comment]
@andreaspeters  please review

**Comment by gagandeepp** [comment]
@andreaspeters  any updates on the above PR?

**Comment by andreaspeters** [comment]
To be honest your PR @gagandeepp is not working. I will keep it because it's a good start, but I have to invest more time before it works.

**Comment by gagandeepp** [comment]
can you please accept my PR and add Hacktoberfest-accepted label to it?
@andreaspeters

**Comment by andreaspeters** [comment]
Thats fair @gagandeepp :+1:

**Comment by gagandeepp** [comment]
thank you @andreaspeters

**Comment by gagandeepp** [comment]
@andreaspeters  Can you please update the label text to **HACKTOBERFEST-ACCEPTED** ??

**Comment by andreaspeters** [comment]
I already done.

**Pull request closed without merging**
